name: $(Rev:r)

trigger:
  batch: 'true'
  branches:
    include:
    - master
  paths:
    include:
    - Hub/Service

pool:
  name: Hosted Ubuntu 1604
  
steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    dockerFile: 'Hub/Service/Dockerfile'
    imageName: 'ckaczor/home-monitor-hub-service:$(Build.BuildNumber)'
    includeLatestTag: true

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    action: 'Push an image'
    imageName: 'ckaczor/home-monitor-hub-service:$(Build.BuildNumber)'
    includeLatestTag: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sed -i s/#BUILD_BUILDNUMBER#/$BUILD_BUILDNUMBER/ Hub/Service/deploy/manifest.yaml'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Hub/Service/deploy/manifest.yaml'
    ArtifactName: 'Manifest'
    publishLocation: 'Container'    