---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hub-service
  namespace: home-monitor
  labels:
    app: hub-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-service
  template:
    metadata:
      labels:
        app: hub-service
    spec:
      containers:
      - name: hub-service
        image: ckaczor/home-monitor-hub-service:#BUILD_BUILDNUMBER#
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        securityContext:
          privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: kubernetes
      schedulerName: default-scheduler
---
kind: Service
apiVersion: v1
metadata:
  name: hub-service
spec:
  ports:
  - name: client
    port: 80
  selector:
    app: hub-service
  type: ClusterIP      