FROM microsoft/dotnet:2.2-aspnetcore-runtime-stretch-slim AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk-stretch AS build
WORKDIR /src
COPY ["Weather/Service/Service.csproj", "Weather/Service/"]
COPY ["Weather/Models/Models.csproj", "Weather/Models/"]
RUN dotnet restore "Weather/Service/Service.csproj"
COPY . .
WORKDIR "/src/Weather/Service"
RUN dotnet publish "Service.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "ChrisKaczor.HomeMonitor.Weather.Service.dll"]