/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Almanac: typeof import('./src/components/Almanac.vue')['default']
    CalendarAgenda: typeof import('./src/components/CalendarAgenda.vue')['default']
    CurrentLaundryStatus: typeof import('./src/components/CurrentLaundryStatus.vue')['default']
    CurrentPower: typeof import('./src/components/CurrentPower.vue')['default']
    CurrentWeather: typeof import('./src/components/CurrentWeather.vue')['default']
    DashboardItem: typeof import('./src/components/DashboardItem.vue')['default']
    Indoor: typeof import('./src/components/Indoor.vue')['default']
    IndoorSummary: typeof import('./src/components/IndoorSummary.vue')['default']
    LongPressButton: typeof import('./src/components/LongPressButton.vue')['default']
    NationalDays: typeof import('./src/components/NationalDays.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeRange: typeof import('./src/components/TimeRange.vue')['default']
    ValueChart: typeof import('./src/components/ValueChart.vue')['default']
    WeatherSummary: typeof import('./src/components/WeatherSummary.vue')['default']
  }
}
