name: $(Rev:r)

trigger:
  batch: 'true'
  branches:
    include:
    - master
  paths:
    include:
    - Weather/Service

pool:
  name: Hosted Ubuntu 1604
  
steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    dockerFile: 'Weather/Service/Dockerfile'
    imageName: 'ckaczor/home-monitor-weather-service:$(Build.BuildNumber)'
    includeLatestTag: true

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    action: 'Push an image'
    imageName: 'ckaczor/home-monitor-weather-service:$(Build.BuildNumber)'
    includeLatestTag: true