---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: weather-service
  namespace: home-monitor
  labels:
    app: weather-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-service
  template:
    metadata:
      labels:
        app: weather-service
    spec:
      containers:
      - name: weather-service
        image: ckaczor/home-monitor-weather-service:latest
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: Weather__Queue__Host
          value: weather-queue
        - name: Weather__Queue__User
          valueFrom:
            secretKeyRef:
              name: weather-queue-credentials
              key: username               
        - name: Weather__Queue__Password
          valueFrom:
            secretKeyRef:
              name: weather-queue-credentials
              key: password
        - name: Weather__Database__Host
          value: weather-database
        - name: Weather__Database__User
          valueFrom:
            secretKeyRef:
              name: weather-database-credentials
              key: username               
        - name: Weather__Database__Password
          valueFrom:
            secretKeyRef:
              name: weather-database-credentials
              key: password    
        - name: Hub__Weather
          value: http://hub-service/weatherHub
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: kubernetes
      schedulerName: default-scheduler