name: 1.0.$(Rev:r)

trigger:
  batch: 'true'
  branches:
    include:
    - master
  paths:
    include:
    - Weather/SerialReader

pool:
  name: Hosted Ubuntu 1604
  
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'ckaczor'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: 'Weather/SerialReader'
    tags: '$(Rev:r)'