name: $(Rev:r)

trigger:
  batch: 'true'
  branches:
    include:
    - master
  paths:
    include:
    - Weather/SerialReader

pool:
  name: Hosted Ubuntu 1604
  
steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    dockerFile: 'Weather/SerialReader/Dockerfile'
    imageName: 'ckaczor/home-monitor-weather-serialreader:$(Build.BuildNumber)'
    includeLatestTag: true

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    action: 'Push an image'
    imageName: 'ckaczor/home-monitor-weather-serialreader:$(Build.BuildNumber)'
    includeLatestTag: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sed -i s/#TAG#/$TAG/ Weather/SerialReader/deploy/manifest.yaml'
  env:
    Tag: $(Build.BuildNumber)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Weather/SerialReader/deploy/manifest.yaml'
    ArtifactName: 'Manifest'
    publishLocation: 'Container'