---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: weather-serial-reader
  namespace: home-monitor
  labels:
    app: weather-serial-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-serial-reader
  template:
    metadata:
      labels:
        app: weather-serial-reader
    spec:
      containers:
      - name: weather-serial-reader
        image: ckaczor/home-monitor-weather-serialreader:latest
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: Weather__Queue__Host
          value: weather-queue
        - name: Weather__Queue__User
          valueFrom:
            secretKeyRef:
              name: weather-queue-credentials
              key: username               
        - name: Weather__Queue__Password
          valueFrom:
            secretKeyRef:
              name: weather-queue-credentials
              key: password   
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: weather
      schedulerName: default-scheduler