variables:
  Major: '1'
  Minor: '0'
  Patch: '0'

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - Weather/Models/**/*

steps:
- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: 'Weather/Models/Models.csproj'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: 'Weather/Models/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '2eb33313-2dc4-435d-ab24-74b653cdd7bc'