variables:
  majorMinorVersion: 1.0
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]
  buildConfiguration: 'Release'

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - Weather/Models

steps:
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    configuration: $(BuildConfiguration)
    packagesToPack: 'Weather/Models/Models.csproj'
    versioningScheme: byBuildNumber
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: 'Weather/Models/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '2eb33313-2dc4-435d-ab24-74b653cdd7bc'
